web:
    build: ./docker/nginx
    ports:
        - "8001:8001"
    links:
        - node:node

node:
    build: ./src
    ports:
        - "3001:3001"
        - "8080:8080"
    links:
        - db:db

db:
    image: mongo
    ports:
        - "27017:27017"
